# Dockerfile
FROM python:3.12

# Imposta la cartella di lavoro
WORKDIR /usr/src/app

# Copia requirements.txt e installa le dipendenze
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copia il resto dell'app
COPY . .

# Espone la porta
EXPOSE 3000

# Comando per avviare l'app
CMD ["python", "app.py"]
